### ISSUE TITLE
支持Linux与MacOS

### ISSUE THREAD

**Issue by tonyho** [rerender2021/echo#1]
考虑支持Linux和MacOS吗？ 尤其是Linux。

**Comment by rerender2021** [comment]
我想应该是无法支持linux或mac的，因为我只有windows的开发设备。

不过这个软件的一些组件可能可以复用，因为这些组件本质上都是python起的服务器，希望对你有帮助：

- 语音翻译：https://github.com/rerender2021/ASR-API
- 英语翻译：https://github.com/rerender2021/NLP-API/
