### ISSUE TITLE
启动ASR server报错，怀疑是端口占用导致： [Errno 10013] error while attempting to bind on address ('127.0.0.1', 8200): 以一种访问权限不允许的方式做了一个访问套接字的尝试。

### ISSUE THREAD

**Issue by kaikanertan** [rerender2021/echo#13]
1. 启动ASR server报错，怀疑是端口占用导致

![start ASR server](https://user-images.githubusercontent.com/46514136/233773556-78b42edf-debf-4aa5-9e41-59c58267f70e.png)

2. 尝试排查，发现8200端口被占用，是否可换用其他端口运行ASR server。

![port debug](https://user-images.githubusercontent.com/46514136/233773666-77f4f093-2875-46b0-a93d-ac57b1629745.png)

**Comment by rerender2021** [comment]
> 是否可换用其他端口运行ASR server

目前没有支持自定义端口，在之后的更新中会加上这个功能。

现在的话只有暂时先关掉winrdlv3，我查了一下应该是可以关掉的：https://www.zhihu.com/question/40974912。

**Comment by kaikanertan** [comment]
> 

感谢回复。
等待开放自定义端口功能上线。

**Comment by kaikanertan** [comment]
> > 是否可换用其他端口运行ASR server
> 
> 目前没有支持自定义端口，在之后的更新中会加上这个功能。
> 
> 现在的话只有暂时先关掉winrdlv3，我查了一下应该是可以关掉的：https://www.zhihu.com/question/40974912

感谢回复。
等待开放自定义端口功能上线。

**Comment by rerender2021** [comment]
> > > 是否可换用其他端口运行ASR server
> > 
> > 
> > 目前没有支持自定义端口，在之后的更新中会加上这个功能。
> > 现在的话只有暂时先关掉winrdlv3，我查了一下应该是可以关掉的：https://www.zhihu.com/question/40974912
> 
> 感谢回复。 等待开放自定义端口功能上线。

已支持，可以试试：https://github.com/rerender2021/echo/releases/tag/preview%2Fcustom-port

**Comment by kaikanertan** [comment]
> > > > 是否可换用其他端口运行ASR server
> > > 
> > > 
> > > 目前没有支持自定义端口，在之后的更新中会加上这个功能。
> > > 现在的话只有暂时先关掉winrdlv3，我查了一下应该是可以关掉的：https://www.zhihu.com/question/40974912
> > 
> > 
> > 感谢回复。 等待开放自定义端口功能上线。
> 
> 已支持，可以试试：https://github.com/rerender2021/echo/releases/tag/preview%2Fcustom-port

首先很感谢。已更新，还是有一个问题，感觉还是端口。

1. config如下：

![config](https://user-images.githubusercontent.com/46514136/234751443-1bc47e79-3aaf-44e9-ae4f-8a30f105ce9b.png)

2. 错误如下：

![error](https://user-images.githubusercontent.com/46514136/234751713-238aaa85-1d5c-4c19-b044-29a8c721661b.png)

问题可能还是端口占用:

![image](https://user-images.githubusercontent.com/46514136/234752656-275f0af8-7ee0-41c0-9828-44cae8350ad8.png)

3: config 文件确实生效了：

![ASR](https://user-images.githubusercontent.com/46514136/234753005-3358f6e4-9e1f-4fd7-a4e0-8f43b55fb366.png)

![NLP](https://user-images.githubusercontent.com/46514136/234753063-9987695a-9183-405f-b0a7-5158d5e9367c.png)

**Comment by rerender2021** [comment]
@kaikanertan 是的，看来8210那个端口也需要自定义才行

**Comment by rerender2021** [comment]
好了，把它也弄来可以自定义了，这次只需要更新16M的exe：

https://github.com/rerender2021/echo/releases/download/preview%2Fcustom-port/echo-vosk-port.zip

新加了一个字段：asrSocketPort

这样设置：

```json
{
    "timeout": 3500,
    "asrPort": 8222,
    "asrSocketPort": 8333,
    "nlpPort": 8111
}
```

**Comment by rerender2021** [comment]
一共由3个接口：

- 我封装的翻译的：nlpPort
- 我封装的语音识别的：asrPort
- 语音识别库内部的：asrSocketPort

之前只自定义了我封装的相关的接口

**Comment by kaikanertan** [comment]
> 一共有3个接口：
> 
> * 我封装的翻译的：nlpPort
> * 我封装的语音识别的：asrPort
> * 语音识别库内部的：asrSocketPort
> 
> 之前只自定义了我封装的相关的接口

完美解决。
