### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by jsRuner** [rerender2021/echo#3]
建议增加日志收集排除问题。
例如写入文件，这样直接提供日志给开发者。

**Comment by rerender2021** [comment]
谢谢你的建议，目前排查问题是比较麻烦，需要下载调试包看报错信息

**Comment by rerender2021** [comment]
注意到标题是“无法使用”，如果目前无法使用的话，可以尝试下载调试包，看一下报错信息：https://github.com/rerender2021/echo/releases/tag/1.0.0

**Comment by rerender2021** [comment]
release 1.2.0 新增了这个功能：https://github.com/rerender2021/echo/releases/tag/1.2.0
