### ISSUE TITLE
asr failed: connect ECONNREFUSED 127.0.0.1:8200

### ISSUE THREAD

**Issue by KaLokChiu** [rerender2021/echo#4]
调试报错asr failed: connect ECONNREFUSED 127.0.0.1:8200
NLP-API.exe启动无报错
ASR-API.exe启动报错闪退

**Comment by rerender2021** [comment]
“asr failed: connect ECONNREFUSED 127.0.0.1:8200” 已经是结果了，报错的原因应该在前面，可以完整复制相关输出，或者完整截图贴一下来排查。

"ASR-API.exe启动报错闪退"，它这个不能直接点exe，要在同级目录下控制台输入.\ASR-API.exe，这样打开的话才不会闪退。

不过不需要单独打开它来排查，用调试包就可以，调试包会自动调起它。

**Comment by QJL000** [comment]
![QQ截图20230314195522](https://user-images.githubusercontent.com/71762722/224993689-a15d0a1f-7031-4fc5-891e-298847e0b12c.png)
![QQ截图20230314195534](https://user-images.githubusercontent.com/71762722/224993707-5093022d-a9f6-44ce-926a-290dfa60bf4d.png)

**Comment by rerender2021** [comment]
> ![QQ截图20230314195522](https://user-images.githubusercontent.com/71762722/224993689-a15d0a1f-7031-4fc5-891e-298847e0b12c.png) ![QQ截图20230314195534](https://user-images.githubusercontent.com/71762722/224993707-5093022d-a9f6-44ce-926a-290dfa60bf4d.png)

导致报错的在这里：
![image](https://user-images.githubusercontent.com/87927336/225014129-465ed582-33eb-4022-a9e6-3d90feccb1d6.png)

看上去好像在编译什么。你电脑上是有装c++相关编译的环境/工具吗

**Comment by QJL000** [comment]
对的，c++的编译器mingw是有装的

**Comment by rerender2021** [comment]
![image](https://user-images.githubusercontent.com/87927336/225014580-a3dd1a1a-44c5-425d-bf18-21e52a1b2282.png)

我电脑上正常启动的话，输出应该是这样的，它好像会尝试去找g++，你的估计就是找到了，然后它会尝试去编译，用c++高性能的，但是编译出问题了

**Comment by rerender2021** [comment]
> 哦！所以你是没有装，我的装了，看报错，是没有Python.h这个头文件，只要解决这个就行了吧

是的，我猜是这个原因，不过我没试过怎么让它找到。。有2种方式可以使得正常使用：

- python.h之类的让它找到，让它编译c++高性能的版本
- 让它找不到g++。。默认用python的实现

**Comment by rerender2021** [comment]
> 好的，非常感谢，我去试试

不客气~

**Comment by rerender2021** [comment]
补充：移除g++环境变量的方式：

- 找到设置环境变量的地方：可以参考 https://new.qq.com/rain/a/20211202A08CCW00
- 找到g++相关环境变量的设置


 如果这里没有，就点进path里面看有没有
![image](https://user-images.githubusercontent.com/87927336/228131845-1255b212-f960-4e2a-b99e-1b322312294a.png)

点进path看会是这样：
![image](https://user-images.githubusercontent.com/87927336/228132036-d1cb0010-ea3c-4cb1-9a16-3635d035b627.png)

- 如果还是没有，那再看一下下面“系统变量”（刚才看的是xxx的用户变量），还是去path里面找

![image](https://user-images.githubusercontent.com/87927336/228132115-5ba94877-2334-4517-b31d-fa6a5195daa8.png)

**Comment by rerender2021** [comment]
> 

![image](https://user-images.githubusercontent.com/87927336/228251092-d1d9f03c-3d6f-470b-92e8-90f2dee9f2c0.png)

就是要确保g++ not available的情况去运行，上面贴的报错，是在g++ not available的情况下运行的吗

**Comment by rerender2021** [comment]
打开控制台输入g++ ，如果出现

```bash
'g++' is not recognized as an internal or external command,
operable program or batch file.
```

这样就对了，说明g++已经移除了，可以这样检查一下。

**Comment by yy35959199** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/87927336/228251092-d1d9f03c-3d6f-470b-92e8-90f2dee9f2c0.png)
> 
> 就是要确保g++ not available的情况去运行，上面贴的报错，是在g++ not available的情况下运行的吗

啊……不是，我还以为g++ not avaiable的状态是不正常的……就按照上面的提示执行了conda install m2w64-toolchain，现在python的包里有一个g++……那这样的话我去把那个卸掉试试OTZ

**Comment by rerender2021** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/87927336/228251092-d1d9f03c-3d6f-470b-92e8-90f2dee9f2c0.png)
> > 就是要确保g++ not available的情况去运行，上面贴的报错，是在g++ not available的情况下运行的吗
> 
> 啊……不是，我还以为g++ not avaiable的状态是不正常的……就按照上面的提示执行了conda install m2w64-toolchain，现在python的包里有一个g++……那这样的话我去把那个卸掉试试OTZ

会出现编译报错的原因是，它找到了g++；所以解决的方式的移除g++的环境变量，这样它就找不到了，就会用默认的python代码去运行。

**Comment by yy35959199** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/87927336/228251092-d1d9f03c-3d6f-470b-92e8-90f2dee9f2c0.png)
> > > 就是要确保g++ not available的情况去运行，上面贴的报错，是在g++ not available的情况下运行的吗
> > 
> > 
> > 啊……不是，我还以为g++ not avaiable的状态是不正常的……就按照上面的提示执行了conda install m2w64-toolchain，现在python的包里有一个g++……那这样的话我去把那个卸掉试试OTZ
> 
> 会出现编译报错的原因是，它找到了g++；所以解决的方式是移除g++的环境变量，这样它就找不到了，就会用默认的python代码去运行。

好的，非常感谢，现在GPU和非GPU的版本都正常运行了，唯一的问题是输入设备改为立体声混音后一直显示输入最大音量为0%……还在搜索原因和解决方案OTZ

**Comment by rerender2021** [comment]
> 你好，我这是什么问题？ ![2](https://user-images.githubusercontent.com/116427924/232530451-e8414039-452c-4a29-98a5-4321a3d976fb.PNG) ![3](https://user-images.githubusercontent.com/116427924/232530475-e0434088-a1f2-4316-95aa-a9127ad458db.PNG) ![4](https://user-images.githubusercontent.com/116427924/232530483-e043aac8-c8f4-462a-aa01-85d0832264aa.PNG) ![1](https://user-images.githubusercontent.com/116427924/232530491-65e2aaa0-16be-4c00-bd03-6a360a627ca0.PNG)

从截图来看，问题是没有进行语音识别。

现象是正常播放视频，但是没有翻译的字幕吗？

另外，在电脑设置中有确认是立体声混响吗，如果正常的话，它下面的测试麦克风会有反应：

![image](https://user-images.githubusercontent.com/87927336/232791785-f4ef5fa4-380b-45c8-9d3a-093c44df625e.png)

**Comment by NIDIE2** [comment]
感谢，解决了。但似乎是扬声器可以，有线耳机却没有声音跳动？

**Comment by rerender2021** [comment]
> 感谢，解决了。但似乎是扬声器可以，有线耳机却没有声音跳动？

我试过有线耳机倒是可以，就是那种最普通的有线耳机，不过我只有笔记本电脑，没试过台式机。

**Comment by AABBDAAAQIUYAOHUI** [comment]
![image](https://github.com/rerender2021/echo/assets/148172923/0b80a668-bec9-4d0a-83fb-9419a8b4e49b)
这个是什么问题

**Comment by rerender2021** [comment]
看上去是加载dll失败了，查看一下路径上有没有这个dll呢
![image](https://github.com/rerender2021/echo/assets/87927336/d7eebf46-b270-437a-9329-0298f1ad6979)


> ![image](https://user-images.githubusercontent.com/148172923/275706305-0b80a668-bec9-4d0a-83fb-9419a8b4e49b.png) 这个是什么问题
