### ISSUE TITLE
安装cuda环境，需要手动配置环境变量吗？

### ISSUE THREAD

**Issue by wanguano** [rerender2021/echo#6]
安装 CUDA Toolkit 11.7 Downloads后，还需要手动配置环境变量吗？

**Comment by wanguano** [comment]
安装后，控制台输入：nvcc -V；显示↓
'nvcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rerender2021** [comment]
我印象我装的时候没手动配；
它这样提示的话，应该是没有自动配，需要手动配一下

**Comment by wanguano** [comment]
> 我印象我装的时候没手动配； 它这样提示的话，应该是没有自动配，需要手动配一下

已经配置好环境变量后：
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```
打开了声音：立体混响（输入设备），并且下载好了：echo-use-gpu和asr-server-v1.1.0和nlp-gpu-server，启动后识别无翻译，窗口已经显示：Echo (GPU)

**Comment by rerender2021** [comment]
我发现我设置了github提醒但没起效，issue有回复都收不到。。

**Comment by rerender2021** [comment]
> > 我印象我装的时候没手动配； 它这样提示的话，应该是没有自动配，需要手动配一下
> 
> 已经配置好环境变量后：
> 
> ```
> nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
> Cuda compilation tools, release 11.7, V11.7.64
> Build cuda_11.7.r11.7/compiler.31294372_0
> ```
> 
> 打开了声音：立体混响（输入设备），并且下载好了：echo-use-gpu和asr-server-v1.1.0和nlp-gpu-server，启动后识别无翻译，窗口已经显示：Echo (GPU)

我额外上传了debug用的exe，可以下载看看有什么报错吗：https://github.com/rerender2021/echo/releases/download/preview%2Fuse-gpu/echo-use-gpu-debug.zip

解压缩后和 asr-server-v1.1.0、nlp-gpu-server那些放在一个目录下打开

**Comment by wanguano** [comment]
> > > 我印象我装的时候没手动配； 它这样提示的话，应该是没有自动配，需要手动配一下
> > 
> > 
> > 已经配置好环境变量后：
> > ```
> > nvcc -V
> > nvcc: NVIDIA (R) Cuda compiler driver
> > Copyright (c) 2005-2022 NVIDIA Corporation
> > Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
> > Cuda compilation tools, release 11.7, V11.7.64
> > Build cuda_11.7.r11.7/compiler.31294372_0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 打开了声音：立体混响（输入设备），并且下载好了：echo-use-gpu和asr-server-v1.1.0和nlp-gpu-server，启动后识别无翻译，窗口已经显示：Echo (GPU)
> 
> 我额外上传了debug用的exe，可以下载看看有什么报错吗：https://github.com/rerender2021/echo/releases/download/preview%2Fuse-gpu/echo-use-gpu-debug.zip
> 
> 解压缩后和 asr-server-v1.1.0、nlp-gpu-server那些放在一个目录下打开

- 显示如下：

![](https://mingcloudpic.oss-cn-beijing.aliyuncs.com/img/Snipaste_2023-03-25_22-40-22.png)

![](https://mingcloudpic.oss-cn-beijing.aliyuncs.com/img/Snipaste_2023-03-25_22-40-30.png)

![](https://mingcloudpic.oss-cn-beijing.aliyuncs.com/img/Snipaste_2023-03-25_22-40-43.png)

**Comment by rerender2021** [comment]
没开始语音识别，正常情况会有些识别的结果，比如我这边绿色的文字输出：

![image](https://user-images.githubusercontent.com/87927336/227724756-7e2e8848-b263-48f4-9e3a-c8c05c3d4e35.png)

你选了输入设备后，播放视频的时候，下面的测试麦克风有蓝色条跳动吗（说明这个设备有效）：

![image](https://user-images.githubusercontent.com/87927336/227724876-16363a9c-47e9-4a68-bdd4-54004305309f.png)

**Comment by rerender2021** [comment]
你之前用过1.0.0的吗？如果那个可以运行成功的话，这个应该也可以才对。用gpu主要是nlp那个翻译的。

**Comment by rerender2021** [comment]
> 你之前用过1.0.0的吗？如果那个可以运行成功的话，这个应该也可以才对。用gpu主要是nlp那个翻译的。

你可以试试换用1.0.0的那个语音服务器，方法是把asr-server-v1.1.0文件夹暂时挪到别的地方，不要和exe放在同级目录，让它去找1.0.0的asr-server

**Comment by wanguano** [comment]
> > 你之前用过1.0.0的吗？如果那个可以运行成功的话，这个应该也可以才对。用gpu主要是nlp那个翻译的。
> 
> 你可以试试换用1.0.0的那个语音服务器，方法是把asr-server-v1.1.0文件夹暂时挪到别的地方，不要和exe放在同级目录，让它去找1.0.0的asr-server。
> 
> 运行的时候目录结构：只存在以下3个文件夹
> 
> * asr-server
> * nlp-gpu-server
> * xxx.exe

我测试，之前那个也不行了，那个立体声混响缺失没有反应、跳动

**Comment by wanguano** [comment]
> 

输入设备，只有麦克风 在说话的时候，有跳动

**Comment by rerender2021** [comment]
> > > 你之前用过1.0.0的吗？如果那个可以运行成功的话，这个应该也可以才对。用gpu主要是nlp那个翻译的。
> > 
> > 
> > 你可以试试换用1.0.0的那个语音服务器，方法是把asr-server-v1.1.0文件夹暂时挪到别的地方，不要和exe放在同级目录，让它去找1.0.0的asr-server。
> > 运行的时候目录结构：只存在以下3个文件夹
> > 
> > * asr-server
> > * nlp-gpu-server
> > * xxx.exe
> 
> 我测试，之前那个也不行了，那个立体声混响缺失没有反应、跳动

如果之前有正常过，现在不行了的话，可能是中途不小心改过哪里配置。
